x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE}
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DATABASE}
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: "bleach==6.2.0 boto3==1.38.23 botocore==1.38.23 certifi==2025.4.26 cffi==1.17.1 charset-normalizer==3.4.2 colorama==0.4.6 cryptography==45.0.2 greenlet==3.2.2 idna==3.10 jmespath==1.0.1 kaggle==1.7.4.5 kagglehub==0.3.12 numpy==2.2.6 packaging==25.0 pandas==2.2.3 protobuf==6.31.0 psycopg2==2.9.10 pycparser==2.22 python-dateutil==2.9.0.post0 python-dotenv==1.1.0 python-slugify==8.0.4 pytz==2025.2 PyYAML==6.0.2 requests==2.32.3 s3transfer==0.13.0 setuptools==80.7.1 six==1.17.0 SQLAlchemy==2.0.41 text-unidecode==1.3 tqdm==4.67.1 typing_extensions==4.13.2 tzdata==2025.2 urllib3==2.4.0 webencodings==0.5.1"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
  user: "${AIRFLOW_UID}"
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "airflow db upgrade && \
      airflow users create \
      --username admin \
      --password admin \
      --firstname FIRST_NAME \
      --lastname LAST_NAME \
      --role Admin \
      --email admin@example.org"

volumes:
  postgres-db-volume: